# Generated by Django 2.2.6 on 2020-03-16 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learnmylanguage', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='player',
            old_name='strike',
            new_name='streak',
        ),
        migrations.AddField(
            model_name='player',
            name='email',
            field=models.CharField(default=None, max_length=256),
        ),
    ]
